services:
  - type: web
    name: face-recognition-attendance
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHONIOENCODING
        value: utf-8
